__author__ = 'mohammadrezahosseini'

from github import Github

ACCESS_TOKEN = '8c4296b647da5312faea184007f2d4779ceaa74e' # This is a token generated by GitHub for every Github user

USER = 'ornicar' #The username here
client = Github(ACCESS_TOKEN)
user = client.get_user(USER)
content=[]
for repo in user.get_repos():
    print (repo.name,repo.language,repo.stargazers_count,repo.forks_count)
   #info={repo.name:{'language':repo.language,'star':repo.stargazers_count,'fork':repo.forks_count}}
    info={'language':repo.language,'star':repo.stargazers_count,'fork':repo.forks_count}
    content.append(info)
index=0
star=0
fork=0
i=0
j=0
while (i < len(content)):
    if content[i]['language']==content[j]['language']:
        star=star+content[j]['star']
        fork=fork+content[j]['fork']
        if i != j:
            content.pop(j)
        else:
            j=j+1
    else:
        j=j+1
    if j>= len(content):
        print(content[i]['language'],star,fork)
        star=0
        fork=0
        i=i+1
        j=i



